version: "3.3"
services:
    pinecone:
      build:
        context: ..
        dockerfile: docker/Dockerfile.dev
      ports:
        - "3000:3000"
      volumes:
        - ../src:/app/src
      environment:
        - REACT_APP_NAME=BertholdsBed-dev
        - WATCHPACK_POLLING=true
