version: "3.3"
services:
    pinecone:
      build:
        context: ..
        dockerfile: docker/Dockerfile.hw
        args:
          - REACT_APP_NAME=BertholdsBed-heartwood
      ports:
        - "8282:80"
