version: "3.8"
services:
    pinecone:
      build:
        context: ..
        dockerfile: Dockerfile.hw
        args:
          - REACT_APP_NAME=BertholdsBed-master
      ports:
        - "8080:80"
