name: Deploy to Local NGINX Docker

on:
  workflow_run:
    workflows: [CodeQL]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Deploy
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          npm cache clean --force
          npm run master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
