name: Deploy

concurrency:
  group: hw-${{ toJson(github.event.inputs.array) }}
  cancel-in-progress: false

on:
  workflow_run:
    workflows: [CodeQL]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    environment: heartwood
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Deploy
        run: |
          sudo mkdir /etc/secrets && cd "$_"
          sudo echo > openai_key $OPENAI_KEY && sudo echo > weatherapi_key $WEATHERAPI_KEY
          echo $DOCKER_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin
          cd - && npm run heartwood
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          WEATHERAPI_KEY: ${{ secrets.WEATHERAPI_KEY }}
