name: Deploy

concurrency:
  group: hw-${{ toJson(github.event.inputs.array) }}
  cancel-in-progress: false

on:
  push:
    branches:
      - master
  workflow_run:
    workflows: [Compile/Test]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    environment: heartwood
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build and deploy
        run: |
          sudo -Ss -- mkdir -p /etc/secrets <<< $WRITE_KEY; cd "$_"
          sudo -s eval 'echo > openai_key $OPENAI_KEY; echo > weatherapi_key $WEATHERAPI_KEY'
          echo $DOCKER_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin
          cd - && npm run heartwood
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          WEATHERAPI_KEY: ${{ secrets.WEATHERAPI_KEY }}
          WRITE_KEY: ${{ secrets.WRITE_KEY }}
